## MA3K7 Week 11 Rubric Code - Simulation

In [1]:
import numpy as np
from numpy import random

### Simulation of the game for a random 3x3 grid

In [2]:
def move_left(grid, pos, N):
    if N == 1 or N == -2:
        grid[pos] = np.roll(grid[pos], 2)
    elif N == 2 or N == -1:
        grid[pos] = np.roll(grid[pos], 1)
        
    return grid


def move_up(grid, pos, N):
    arr = [grid[0][pos], grid[1][pos], grid[2][pos]]
    
    if N == 2 or N == -1:
        shift_arr = np.roll(arr, 1)
    elif N == 1 or N == -2:
        shift_arr = np.roll(arr, 2)
    elif N == 0:
        shift_arr = arr
        
    for i in range(3):
        grid[i][pos] = shift_arr[i]
        
    return grid


coords = {
    1: (0,0),
    2: (0,1),
    3: (0,2),
    4: (1,0),
    5: (1,1),
    6: (1,2),
    7: (2,0),
    8: (2,1),
    9: (2,2),
}


def basic_moves(grid, i):
    x = np.argwhere(grid==i)[0]
    vertical = x[0] - coords[i][0]
    horizontal = x[1] - coords[i][1]
    x[1] -= horizontal
    
    return move_up(move_left(grid, x[0], horizontal), x[1], vertical)


def same_row(grid, i):
    x = np.argwhere(grid==i)[0]
    new_grid = move_up(move_left(move_up(grid, 0, 1), x[0], 1), 0, 2)
    return new_grid


def outcome(grid, i):
    if i in range(1,4):
        if i == 2 and grid[0][2] == 2:
            same_row(grid, i)
        else:
            basic_moves(grid, i)
    
    elif i in range(4,7):
        x = np.argwhere(grid==i)[0]
        
        if x[0] == 1:
            if i == 5 and grid[1][2] == 5:
                same_row(grid, i)
            else: 
                basic_moves(grid, i)
                
        elif x[0] == 2:
            if x[1] != coords[i][1]:
                new_grid = move_up(grid, coords[i][1], 2)
                basic_moves(new_grid, i)
            else:
                new_grid = move_up(move_left(grid, x[0], 2), coords[i][1], 2)
                basic_moves(new_grid, i)
                
    elif i == 7:
            basic_moves(grid, i)
            
    return grid


def print_result(grid):
    for i in range(1,8):
        grid = outcome(grid,i)
        print(f"Moving {i} into its position:\n", grid, "\n")
    
    if grid[2][1] == 8:
        print("Hence this game is solvable")
    else:
        print("Hence this game is not solvable by this algorithm")
        

def print_final(grid):
    for i in range(1,8):
        grid = outcome(grid,i)
    
    print("The final grid is: \n", grid)
          
    if grid[2][1] == 8:
        print("Hence this game is solvable")
    else:
        print("Hence this game is not solvable by this algorithm")

        
def result(grid):
    for i in range(1,8):
        grid = outcome(grid,i)
    
    if grid[2][1] == 8:
        return True
    else:
        return False


# Generate a random 3x3 grid
numbers = np.arange(1, 10)
np.random.shuffle(numbers)
grid = np.reshape(numbers, (3,3))

print("The starting grid is: \n", grid, "\n")
print_result(grid)

The starting grid is: 
 [[4 6 1]
 [5 7 2]
 [3 8 9]] 

Moving 1 into its position:
 [[1 4 6]
 [5 7 2]
 [3 8 9]] 

Moving 2 into its position:
 [[1 2 6]
 [7 8 5]
 [3 4 9]] 

Moving 3 into its position:
 [[1 2 3]
 [7 8 6]
 [4 9 5]] 

Moving 4 into its position:
 [[1 2 3]
 [4 8 6]
 [5 9 7]] 

Moving 5 into its position:
 [[1 2 3]
 [4 5 6]
 [7 9 8]] 

Moving 6 into its position:
 [[1 2 3]
 [4 5 6]
 [7 9 8]] 

Moving 7 into its position:
 [[1 2 3]
 [4 5 6]
 [7 9 8]] 

Hence this game is not solvable by this algorithm


### Simulation of the game for the example given in the question

In [3]:
grid1 = np.array([[3,5,8],[6,1,7],[9,2,4]])

print("The starting grid is: \n", grid1, "\n")
print_final(grid1)

The starting grid is: 
 [[3 5 8]
 [6 1 7]
 [9 2 4]] 

The final grid is: 
 [[1 2 3]
 [4 5 6]
 [7 9 8]]
Hence this game is not solvable by this algorithm


### Simulation of the game when swapping 3 and 5 in the example given in the question

In [4]:
grid2 = np.array([[5,3,8],[6,1,7],[9,2,4]])

print("The starting grid is: \n", grid2, "\n")
print_final(grid2)

The starting grid is: 
 [[5 3 8]
 [6 1 7]
 [9 2 4]] 

The final grid is: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Hence this game is solvable


### Extension - counts the number of solvable games, generates a mean number of solvable games

In [6]:
def count():
    count = 0
    for _ in range(10000):
        numbers = np.arange(1, 10)
        np.random.shuffle(numbers)
        grid = np.reshape(numbers, (3,3))
        
        if result(grid) == True:
            count += 1
    
    return count


def mean(N):
    total = 0
    for _ in range(N):
        total += count()
    
    mean = total / N
    
    return mean

mean(20)

5008.15